export const data = [
  {
    timestamp: new Date().toISOString(),
    gradeLevel: 3,
    subjectArea: "Literature",
    concept: "character-traits-and-actions",
    knowledge: "What are some words that describe how a character acts?",
    comprehension: "Describe characters in a story (e.g., their traits, motivations or feelings)[cite: 4].",
    application: "How would you show a character's bravery through their actions in a story?",
    analysis: "Explain how a character's actions contribute to the sequence of events[cite: 4].",
    synthesis: "Create a new character for a familiar story and explain how their traits would change the plot.",
    evaluation: "Which character's actions in a story you've read were most important to the story's outcome? Why?"
  },
  {
    timestamp: new Date().toISOString(),
    gradeLevel: 3,
    subjectArea: "Literature",
    concept: "main-idea-and-story-elements",
    knowledge: "What is the main idea of a story?",
    comprehension: "Recount stories, including fables, folktales, and myths from diverse cultures; determine the lesson, moral, or central message (main idea)[cite: 2, 3].",
    application: "How would you find the central message in a new folktale?",
    analysis: "Explain how the lesson, moral, or central message is conveyed through key details in the text[cite: 3].",
    synthesis: "Create a new fable that teaches a specific moral.",
    evaluation: "Is it more important to understand the plot or the main idea of a story? Explain your reasoning."
  },
  {
    timestamp: new Date().toISOString(),
    gradeLevel: 3,
    subjectArea: "Literature",
    concept: "literal-and-nonliteral-language",
    knowledge: "What is literal language? What is nonliteral language?",
    comprehension: "Determine the meaning of words and phrases as they are used in a text, distinguishing literal from nonliteral language[cite: 5].",
    application: "How would you use sentence-level context (synonym, antonym, definition, examples) to comprehend the meaning of a word or phrase[cite: 14]?",
    analysis: "Analyze how an author uses nonliteral language to create a certain effect.",
    synthesis: "Write a short paragraph using both literal and nonliteral language.",
    evaluation: "Is understanding literal or nonliteral language more important for comprehending a story? Why?"
  },
  {
    timestamp: new Date().toISOString(),
    gradeLevel: 3,
    subjectArea: "Literature",
    concept: "text-structure-and-development",
    knowledge: "What are some parts of a story, drama, or poem?",
    comprehension: "Refer to parts of stories, dramas and poems when writing or speaking about a text, using terms such as chapter, scene and stanza[cite: 6].",
    application: "How would you explain how each successive part builds on earlier sections[cite: 7]?",
    analysis: "Analyze how a specific chapter or scene contributes to the overall story.",
    synthesis: "Reorganize the chapters of a short story to see how it affects the flow.",
    evaluation: "Do chapters or scenes contribute more to building a story? Justify your answer."
  },
  {
    timestamp: new Date().toISOString(),
    gradeLevel: 3,
    subjectArea: "Literature",
    concept: "point-of-view",
    knowledge: "What is a narrator's perspective?",
    comprehension: "Distinguish their own perspective (point of view) from that of the narrator or those of the characters[cite: 7].",
    application: "How would you identify the point of view of a story you are reading?",
    analysis: "Analyze how the narrator's point of view influences what information is revealed in a story.",
    synthesis: "Rewrite a scene from a story from a different character's point of view.",
    evaluation: "Is it easy or difficult to distinguish your own perspective from a character's? Why?"
  },
  {
    timestamp: new Date().toISOString(),
    gradeLevel: 3,
    subjectArea: "Literature",
    concept: "illustrations-and-meaning",
    knowledge: "What are illustrations in a story?",
    comprehension: "Explain how specific aspects of a text's illustrations contribute to what is conveyed by the words in a story (e.g., create mood, emphasize aspects of a character or setting)[cite: 8].",
    application: "How would you use illustrations to help you understand the mood of a story?",
    analysis: "Analyze how illustrations emphasize aspects of a character or setting.",
    synthesis: "Draw an illustration for a story that enhances a specific mood.",
    evaluation: "Are illustrations more helpful in understanding a story than the words themselves? Explain your answer."
  },
  {
    timestamp: new Date().toISOString(),
    gradeLevel: 4,
    subjectArea: "Literature",
    concept: "theme-and-summary",
    knowledge: "What is a theme of a story?",
    comprehension: "Determine the theme of a story, drama or poem from details in the text; summarize the text[cite: 27].",
    application: "How would you identify the theme of a new story after reading it?",
    analysis: "Analyze how specific details in a text reveal the theme of a story, drama, or poem.",
    synthesis: "Write a short story that conveys a specific theme without directly stating it.",
    evaluation: "Is it more important to understand the theme or the plot of a story? Explain your reasoning."
  },
  {
    timestamp: new Date().toISOString(),
    gradeLevel: 4,
    subjectArea: "Literature",
    concept: "character-setting-and-event-description",
    knowledge: "What is a character? What is a setting?",
    comprehension: "Describe in depth a character, setting or event in a story or drama, drawing on specific details in the text (e.g., a character's thoughts, words or actions)[cite: 28].",
    application: "How would you use a character's dialogue to describe their personality?",
    analysis: "Analyze how a character's thoughts, words, or actions contribute to their overall description in a story.",
    synthesis: "Create a detailed description of a new setting for an existing story.",
    evaluation: "Which is more challenging to describe in depth: a character, a setting, or an event? Why?"
  },
  {
    timestamp: new Date().toISOString(),
    gradeLevel: 4,
    subjectArea: "Literature",
    concept: "meaning-of-words-and-phrases",
    knowledge: "What are some ways to determine the meaning of unknown words?",
    comprehension: "Determine the meaning of words and phrases as they are used in a text, including those that allude to significant characters found in mythology (e.g., Herculean)[cite: 29].",
    application: "How would you use context (antonym, examples, inferences, definition, synonym) to determine the meaning of a word or phrase[cite: 37]?",
    analysis: "Analyze how allusions to mythology impact the meaning of a word or phrase.",
    synthesis: "Write a sentence using a word that alludes to a mythological character.",
    evaluation: "Is it more helpful to use context clues or a dictionary to determine the meaning of a word? Why?"
  },
  {
    timestamp: new Date().toISOString(),
    gradeLevel: 4,
    subjectArea: "Literature",
    concept: "structural-elements-of-genres",
    knowledge: "What are the differences between poems, dramas, and prose?",
    comprehension: "Explain major differences between poems, drama and prose and refer to the structural elements of poems (e.g., verse, rhythm, meter) and drama (e.g., casts of characters, settings, descriptions, dialogue, stage directions) when writing or speaking about a text[cite: 30].",
    application: "How would you use the structural elements of a drama to write a short scene?",
    analysis: "Analyze how the structural elements of a poem contribute to its meaning.",
    synthesis: "Create a short text that combines elements of prose and poetry.",
    evaluation: "Which genre's structural elements are most important for conveying its message? Why?"
  },
  {
    timestamp: new Date().toISOString(),
    gradeLevel: 4,
    subjectArea: "Literature",
    concept: "comparing-points-of-view",
    knowledge: "What is first-person narration? What is third-person narration?",
    comprehension: "Compare and contrast the point of view from which different stories are narrated, including the difference between first- and third-person narrations[cite: 31].",
    application: "How would you rewrite a paragraph from a first-person narration into a third-person narration?",
    analysis: "Analyze how a change in narration point of view can affect the reader's understanding of a story.",
    synthesis: "Write a short story told from two different points of view.",
    evaluation: "Is first-person or third-person narration more effective for telling certain types of stories? Why?"
  },
  {
    timestamp: new Date().toISOString(),
    gradeLevel: 4,
    subjectArea: "Literature",
    concept: "connecting-text-and-presentations",
    knowledge: "What is a visual presentation of a story?",
    comprehension: "Make connections between the text of a story or drama and a visual or oral presentation of the text, identifying where each version reflects specific descriptions and directions in the text[cite: 32].",
    application: "How would you use a visual presentation to highlight a specific description from a text?",
    analysis: "Analyze how a visual presentation of a story interprets specific descriptions and directions from the text.",
    synthesis: "Create a storyboard for a scene from a book you've read, based on the text's descriptions.",
    evaluation: "Is it more helpful to read a story or watch a visual presentation of it to understand specific details? Explain why."
  },
  {
    timestamp: new Date().toISOString(),
    gradeLevel: 5,
    subjectArea: "Literature",
    concept: "quoting-textual-evidence",
    knowledge: "What does it mean to quote from a text?",
    comprehension: "Quote accurately from a text when explaining what the text says explicitly and when drawing inferences from the text[cite: 59].",
    application: "How would you use a direct quote to support an inference about a character's motivation?",
    analysis: "Analyze how quoting accurately from a text strengthens an explanation or inference.",
    synthesis: "Formulate a response to a question about a story by integrating multiple direct quotes.",
    evaluation: "Is quoting directly from a text always the best way to support an answer? Why or why not?"
  },
  {
    timestamp: new Date().toISOString(),
    gradeLevel: 5,
    subjectArea: "Literature",
    concept: "theme-and-character-response",
    knowledge: "What is the theme of a story?",
    comprehension: "Determine the theme of a story, drama, or poem, including how characters respond to challenges or how the speaker in a poem reflects upon a topic[cite: 60].",
    application: "How would you identify the theme of a story based on how a character overcomes a challenge?",
    analysis: "Analyze how characters' responses to challenges contribute to the overall theme of a story.",
    synthesis: "Write a short story where the main character's struggle directly reveals the theme.",
    evaluation: "Is a character's response to a challenge more important for understanding the theme than the challenge itself? Explain."
  },
  {
    timestamp: new Date().toISOString(),
    gradeLevel: 5,
    subjectArea: "Literature",
    concept: "comparing-and-contrasting-elements",
    knowledge: "What does it mean to compare and contrast?",
    comprehension: "Compare and contrast two or more characters, settings or events in a story or drama, drawing on specific details in the text (e.g., how characters interact)[cite: 61].",
    application: "How would you create a Venn diagram to compare and contrast two characters from a story?",
    analysis: "Analyze how the interactions between characters highlight their similarities and differences.",
    synthesis: "Write a short scene where two characters with contrasting traits interact.",
    evaluation: "Is it more valuable to compare or contrast elements of a story? Justify your answer."
  },
  {
    timestamp: new Date().toISOString(),
    gradeLevel: 5,
    subjectArea: "Literature",
    concept: "figurative-language-meaning",
    knowledge: "What is figurative language?",
    comprehension: "Determine the meaning of words and phrases as they are used in a text, including figurative language such as metaphors and similes[cite: 62].",
    application: "How would you rephrase a simile into literal language?",
    analysis: "Analyze how the use of metaphors and similes impacts the imagery and understanding of a text.",
    synthesis: "Compose a short poem or description using at least two examples of figurative language.",
    evaluation: "Does figurative language make a text easier or harder to understand? Explain your opinion."
  },
  {
    timestamp: new Date().toISOString(),
    gradeLevel: 5,
    subjectArea: "Literature",
    concept: "overall-structure-of-text",
    knowledge: "What are chapters, scenes, and stanzas?",
    comprehension: "Explain how a series of chapters, scenes or stanzas fits together to provide the overall structure of a particular story, drama or poem[cite: 63].",
    application: "How would you organize a new story into logical chapters?",
    analysis: "Analyze how the arrangement of chapters or stanzas contributes to the flow and meaning of a text.",
    synthesis: "Outline a plot for a short story, detailing how each chapter will contribute to the overall structure.",
    evaluation: "Is the overall structure of a text more important than the individual details within it? Why or why not?"
  },
  {
    timestamp: new Date().toISOString(),
    gradeLevel: 5,
    subjectArea: "Literature",
    concept: "narrator-or-speaker-point-of-view",
    knowledge: "What is a narrator's point of view?",
    comprehension: "Describe how a narrator's or speaker's point of view influences how events are described[cite: 64].",
    application: "How would you identify the narrator's bias in a story?",
    analysis: "Analyze how a biased narrator's perspective can shape the reader's understanding of events.",
    synthesis: "Rewrite a short event from a story from a heavily biased point of view.",
    evaluation: "Is it more important to understand the events of a story or the narrator's perspective on those events? Explain."
  },
  {
    timestamp: new Date().toISOString(),
    gradeLevel: 6,
    subjectArea: "Literature",
    concept: "citing-textual-evidence",
    knowledge: "What is textual evidence?",
    comprehension: "Cite textual evidence to support analysis of what the text says explicitly as well as inferences drawn from the text[cite: 79].",
    application: "How would you find and use textual evidence to support an inference about a character's motivation?",
    analysis: "Analyze how the strength of textual evidence impacts the validity of an analysis or inference.",
    synthesis: "Construct an argument about a story's theme, supporting it with multiple pieces of textual evidence.",
    evaluation: "Is it always necessary to cite textual evidence when discussing a story? Why or why not?"
  },
  {
    timestamp: new Date().toISOString(),
    gradeLevel: 6,
    subjectArea: "Literature",
    concept: "theme-and-objective-summary",
    knowledge: "What is a theme?",
    comprehension: "Determine a theme of a text and how it is conveyed through particular details; provide a summary of the text distinct from personal opinions or judgments[cite: 80, 81].",
    application: "How would you create an objective summary of a story you've read?",
    analysis: "Analyze how specific details in a text contribute to the development of its theme.",
    synthesis: "Write an objective summary for a story that clearly highlights its central theme.",
    evaluation: "Is it challenging to provide a summary distinct from personal opinions? Why or why not?"
  },
  {
    timestamp: new Date().toISOString(),
    gradeLevel: 6,
    subjectArea: "Literature",
    concept: "plot-unfolding-and-character-change",
    knowledge: "What is a plot?",
    comprehension: "Describe how a particular story's or drama's plot unfolds in a series of episodes as well as how the characters respond or change as the plot moves toward a resolution[cite: 82].",
    application: "How would you map out the key episodes in a story's plot?",
    analysis: "Analyze how a specific episode in a story influences a character's change or response.",
    synthesis: "Create an alternative resolution for a story and explain how the characters would respond differently.",
    evaluation: "Is a character's change more impactful on the plot than the initial inciting incident? Explain your view."
  },
  {
    timestamp: new Date().toISOString(),
    gradeLevel: 6,
    subjectArea: "Literature",
    concept: "impact-of-word-choice",
    knowledge: "What is connotative meaning?",
    comprehension: "Determine the meaning of words and phrases as they are used in a text, including figurative and connotative meanings; analyze the impact of a specific word choice on meaning and tone[cite: 83, 84].",
    application: "How would you identify words with strong connotative meanings in a text?",
    analysis: "Analyze how an author's specific word choice contributes to the overall tone of a passage.",
    synthesis: "Rewrite a sentence to change its tone by altering specific word choices.",
    evaluation: "Is a single word choice capable of significantly changing the meaning and tone of an entire paragraph? Explain."
  },
  {
    timestamp: new Date().toISOString(),
    gradeLevel: 6,
    subjectArea: "Literature",
    concept: "text-structure-and-theme",
    knowledge: "What is the structure of a text?",
    comprehension: "Analyze how a particular sentence, chapter, scene or stanza fits into the overall structure of a text and contributes to the development of the theme, setting or plot[cite: 85].",
    application: "How would you identify the function of a specific scene in developing the plot?",
    analysis: "Analyze how the placement of a key sentence impacts the reader's understanding of the setting.",
    synthesis: "Design a new chapter for a story, explaining how it would contribute to its theme and plot.",
    evaluation: "Which structural element (sentence, chapter, scene, stanza) has the greatest impact on a text's overall theme? Justify your opinion."
  },
  {
    timestamp: new Date().toISOString(),
    gradeLevel: 6,
    subjectArea: "Literature",
    concept: "author-develops-point-of-view",
    knowledge: "What is a narrator's point of view?",
    comprehension: "Explain how an author develops the point of view of the narrator or speaker in a text[cite: 86].",
    application: "How would you identify an author's techniques for establishing a narrator's perspective?",
    analysis: "Analyze how an author uses specific literary devices to shape the narrator's point of view.",
    synthesis: "Write a short passage demonstrating how an author can create a specific point of view through descriptive language.",
    evaluation: "Is it more effective for an author to subtly develop point of view or state it explicitly? Why?"
  },
  {
    timestamp: new Date().toISOString(),
    gradeLevel: 7,
    subjectArea: "Literature",
    concept: "textual-evidence-and-inferences",
    knowledge: "What is an inference?",
    comprehension: "Cite several pieces of textual evidence to support analysis of what the text says explicitly as well as inferences drawn from the text[cite: 107].",
    application: "How would you select the strongest textual evidence to support a complex inference?",
    analysis: "Analyze how multiple pieces of textual evidence collectively support a sophisticated inference.",
    synthesis: "Develop an argument about a character's complex motivation, citing various pieces of textual evidence.",
    evaluation: "When is it more important to rely on explicit textual evidence versus drawing inferences? Explain."
  },
  {
    timestamp: new Date().toISOString(),
    gradeLevel: 7,
    subjectArea: "Literature",
    concept: "theme-development-and-summary",
    knowledge: "How does a theme develop in a text?",
    comprehension: "Determine a theme of a text and analyze its development over the course of the text; provide an objective summary of the text[cite: 108, 109].",
    application: "How would you track the evolution of a theme across different sections of a story?",
    analysis: "Analyze how recurring motifs or symbols contribute to the development of a theme.",
    synthesis: "Create a visual representation showing the development of a theme throughout a story.",
    evaluation: "Is it more challenging to analyze a theme's development or to provide an objective summary? Why?"
  },
  {
    timestamp: new Date().toISOString(),
    gradeLevel: 7,
    subjectArea: "Literature",
    concept: "elements-interaction",
    knowledge: "How do elements of a story work together?",
    comprehension: "Analyze how particular elements of a story or drama interact (e.g., how setting shapes the characters or plot)[cite: 110].",
    application: "How would you illustrate the cause-and-effect relationship between a setting and a character's development?",
    analysis: "Analyze how a specific conflict between characters is shaped by the story's setting.",
    synthesis: "Design a story where the setting is an active force, directly shaping characters and plot.",
    evaluation: "Which interaction between story elements (e.g., setting-character, character-plot) is most critical for a compelling narrative? Justify your choice."
  },
  {
    timestamp: new Date().toISOString(),
    gradeLevel: 7,
    subjectArea: "Literature",
    concept: "impact-of-sound-devices",
    knowledge: "What is alliteration?",
    comprehension: "Determine the meaning of words and phrases as they are used in a text, including figurative and connotative meanings; analyze the impact of rhymes and other repetitions of sounds (e.g., alliteration) on a specific verse or stanza of a poem or section of a story or drama[cite: 111, 112].",
    application: "How would you identify examples of alliteration in a poem?",
    analysis: "Analyze how the repetition of sounds in a poem contributes to its mood or meaning.",
    synthesis: "Write a short poem that intentionally uses alliteration to create a specific auditory effect.",
    evaluation: "Do sound devices like alliteration enhance or detract from the clarity of a text? Explain."
  },
  {
    timestamp: new Date().toISOString(),
    gradeLevel: 7,
    subjectArea: "Literature",
    concept: "form-and-structure-meaning",
    knowledge: "What are different forms of drama or poetry?",
    comprehension: "Analyze how a drama's or poem's form or structure contributes to its meaning[cite: 113].",
    application: "How would you explain how a sonnet's structure influences its content?",
    analysis: "Analyze how the unconventional structure of a poem impacts its interpretation.",
    synthesis: "Create a short drama that uses a specific structural element (e.g., soliloquies) to convey a hidden meaning.",
    evaluation: "Is the form or the content of a poem more important for understanding its meaning? Justify your answer."
  },
  {
    timestamp: new Date().toISOString(),
    gradeLevel: 7,
    subjectArea: "Literature",
    concept: "contrasting-viewpoints",
    knowledge: "What is a perspective?",
    comprehension: "Analyze how an author develops and contrasts the various perspectives (viewpoints) of different characters or narrators in a text[cite: 115].",
    application: "How would you compare and contrast the viewpoints of two characters on the same event?",
    analysis: "Analyze how the contrasting perspectives of characters create tension or conflict in a story.",
    synthesis: "Write a dialogue between two characters who hold vastly different viewpoints on a shared experience.",
    evaluation: "Is it more effective for an author to present multiple viewpoints or to focus on one dominant perspective? Why?"
  },
  {
    timestamp: new Date().toISOString(),
    gradeLevel: 8,
    subjectArea: "Literature",
    concept: "strongest-textual-evidence",
    knowledge: "What is explicit textual evidence?",
    comprehension: "Cite the textual evidence that most strongly supports an analysis of what the text says explicitly as well as inferences drawn from the text[cite: 136].",
    application: "How would you justify your selection of the 'most strongly' supportive evidence for an analysis?",
    analysis: "Analyze why certain pieces of textual evidence are stronger than others in supporting a particular inference.",
    synthesis: "Formulate a persuasive argument about a literary interpretation, relying on the most compelling textual evidence.",
    evaluation: "Is it always clear which textual evidence is the 'most strongly' supportive? What makes some evidence stronger than others?"
  },
  {
    timestamp: new Date().toISOString(),
    gradeLevel: 8,
    subjectArea: "Literature",
    concept: "theme-development-and-elements",
    knowledge: "How does theme relate to characters, setting, and plot?",
    comprehension: "Determine a theme of a text and analyze its development over the course of the text, including its relationship to the characters, setting, and plot[cite: 137].",
    application: "How would you trace the development of a theme through specific interactions between characters and the setting?",
    analysis: "Analyze how changes in setting or plot directly impact the unfolding of the story's theme.",
    synthesis: "Create a story outline where the theme is intricately woven into the characters' arcs and plot twists.",
    evaluation: "Which element—character, setting, or plot—is most influential in the development of a text's theme? Explain."
  },
  {
    timestamp: new Date().toISOString(),
    gradeLevel: 8,
    subjectArea: "Literature",
    concept: "dialogue-and-incident-impact",
    knowledge: "What is dramatic irony?",
    comprehension: "Analyze how particular lines of dialogue or incidents in a story or drama propel the action, reveal aspects of a character or provoke a decision[cite: 138].",
    application: "How would you use a single line of dialogue to reveal a character's hidden motivation?",
    analysis: "Analyze how a seemingly minor incident can significantly propel the action or reveal a crucial character trait.",
    synthesis: "Write a short dramatic scene where a character's decision is provoked by a specific incident.",
    evaluation: "Are dialogue or incidents more effective in revealing character aspects? Justify your answer."
  },
  {
    timestamp: new Date().toISOString(),
    gradeLevel: 8,
    subjectArea: "Literature",
    concept: "impact-of-allusions-and-analogies",
    knowledge: "What is an allusion? What is an analogy?",
    comprehension: "Determine the meaning of words and phrases as they are used in a text, including figurative and connotative meanings; analyze the impact of specific word choices on meaning and tone, including analogies or allusions to other texts[cite: 139, 140].",
    application: "How would you identify an allusion to a historical event in a text?",
    analysis: "Analyze how a literary allusion enriches the meaning or tone of a passage.",
    synthesis: "Compose a short descriptive paragraph that incorporates an allusion to a well-known story.",
    evaluation: "Are analogies or allusions more effective in enhancing the meaning of a text? Explain your reasoning."
  },
  {
    timestamp: new Date().toISOString(),
    gradeLevel: 8,
    subjectArea: "Literature",
    concept: "comparing-text-structures",
    knowledge: "What are different text structures?",
    comprehension: "Compare and contrast the structure of two or more texts and analyze how the differing structure of each text contributes to its meaning and style[cite: 141].",
    application: "How would you explain how the use of flashbacks in one text compares to chronological order in another?",
    analysis: "Analyze how the non-linear structure of a text creates a particular effect on the reader.",
    synthesis: "Outline two different structural approaches for telling the same story, explaining the impact of each.",
    evaluation: "Is a complex text structure always more effective than a simple one for conveying meaning? Why or why not?"
  },
  {
    timestamp: new Date().toISOString(),
    gradeLevel: 8,
    subjectArea: "Literature",
    concept: "point-of-view-and-dramatic-irony",
    knowledge: "What is dramatic irony?",
    comprehension: "Analyze how differences in the points of view of the characters and the audience or reader (e.g., created through the use of dramatic irony) create such effects as suspense or humor[cite: 142].",
    application: "How would you identify instances of dramatic irony in a play or story?",
    analysis: "Analyze how a specific instance of dramatic irony builds suspense in a narrative.",
    synthesis: "Write a short scene that incorporates dramatic irony to create either humor or suspense.",
    evaluation: "Is suspense or humor a more powerful effect created by differences in point of view? Justify your answer."
  }
]